version: 2
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.revision={{.ShortCommit}}

archives:
  - formats:
      - tar.gz
    files:
      - README.md
      - LICENSE
      - packaging/ipneigh_exporter.service
      - packaging/ipneigh_exporter.default

dockers:
  - image_templates:
      - ghcr.io/yuuki/ipneigh_exporter:{{ .Tag }}-amd64
    use: buildx
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - --platform=linux/amd64
    goarch: amd64

  - image_templates:
      - ghcr.io/yuuki/ipneigh_exporter:{{ .Tag }}-arm64
    use: buildx
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - --platform=linux/arm64
    goarch: arm64

docker_manifests:
  - name_template: ghcr.io/yuuki/ipneigh_exporter:{{ .Tag }}
    image_templates:
      - ghcr.io/yuuki/ipneigh_exporter:{{ .Tag }}-amd64
      - ghcr.io/yuuki/ipneigh_exporter:{{ .Tag }}-arm64

  - name_template: ghcr.io/yuuki/ipneigh_exporter:latest
    image_templates:
      - ghcr.io/yuuki/ipneigh_exporter:{{ .Tag }}-amd64
      - ghcr.io/yuuki/ipneigh_exporter:{{ .Tag }}-arm64

checksum:
  name_template: checksums.txt
